import { Router } from "express";
import { createWorkspaceMember, getWorkspaces, getCurrentWorkspace, listWorkspaceMembers, removeWorkspaceMember, updateWorkspaceMember } from "../controllers/workspace.controller";
import { authMiddleware } from "../middlewares/auth.middleware";
export const workspaceRouter = Router();
workspaceRouter.get("/", authMiddleware, getWorkspaces);
workspaceRouter.get("/current", authMiddleware, getCurrentWorkspace);
workspaceRouter.get("/current/members", authMiddleware, listWorkspaceMembers);
workspaceRouter.post("/current/members", authMiddleware, createWorkspaceMember);
workspaceRouter.patch("/current/members/:memberId", authMiddleware, updateWorkspaceMember);
workspaceRouter.delete("/current/members/:memberId", authMiddleware, removeWorkspaceMember);
